/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fluppie;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("das ist heute ein echt toller Tag");
    }
}
