name: Github CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/wrapper-validation-action@v1
      - run: echo "Hello"
      - run: ./gradlew compileJava
      - run: echo "wuppie"

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "das ist ein test"

  job4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "das ist noch ein test"