name: Github CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "das ist wieder einmal ein großer test für die App"
      - run: echo "noch ein log statement"
      - run: echo "das ist das letzte und damit abschließende Log statement"
      - run: echo "das ist wieder einmal ein log statement"
      - run: echo "geil das ist wieder ein log statement"
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "das ist ein test"

  job4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "das ist noch ein test"